export default function PrivacyPolicyPage() {
  return (
    <main className="bg-[#242B7A] min-h-screen py-16 px-4 sm:px-8 text-white">
      <div className="max-w-3xl mx-auto">
        <h1 className="text-4xl font-extrabold mb-2 text-[#D4E333]">
          Privacy Policy
        </h1>
        <p className="mb-8 text-lg text-[#CFABFA]">Last updated: June 2025</p>

        <p className="mb-6">
          This Privacy Policy describes SocialShift's policies and procedures on
          the collection, use, and disclosure of your information when you use
          the Service.
        </p>
        <p className="mb-6">
          We use your personal data to provide and improve the Service. By using
          the Service, you agree to the collection and use of information in
          accordance with this Privacy Policy.
        </p>

        <h2 className="text-2xl font-bold text-[#CFABFA] mt-10 mb-4">
          Interpretation and Definitions
        </h2>
        <h3 className="text-xl font-semibold mb-2">Interpretation</h3>
        <p className="mb-4">
          Words with initial capital letters have meanings defined under the
          following conditions. The following definitions shall have the same
          meaning regardless of whether they appear in singular or plural.
        </p>
        <h3 className="text-xl font-semibold mb-2">Definitions</h3>
        <ul className="mb-6 list-disc list-inside space-y-1 text-[#CFABFA]">
          <li>
            <b>Account</b> means a unique account created for you to access our
            Service or parts of our Service.
          </li>
          <li>
            <b>Affiliate</b> means an entity that controls, is controlled by or
            is under common control with a party.
          </li>
          <li>
            <b>Application</b> refers to Know[ledge], the software program
            provided by the Company.
          </li>
          <li>
            <b>Company</b> (referred to as either "the Company", "We", "Us" or
            "Our") refers to SocialShift, 251 Falls Drive, Wilmington, New
            Castle County, Delaware 19808, United States.
          </li>
          <li>
            <b>Country</b> refers to: Delaware, United States
          </li>
          <li>
            <b>Device</b> means any device that can access the Service such as a
            computer, cellphone, or digital tablet.
          </li>
          <li>
            <b>Personal Data</b> is any information that relates to an
            identified or identifiable individual.
          </li>
          <li>
            <b>Service</b> refers to the Application.
          </li>
          <li>
            <b>Service Provider</b> means any natural or legal person who
            processes the data on behalf of the Company.
          </li>
          <li>
            <b>Third-party Social Media Service</b> refers to any website or
            social network website through which a User can log in or create an
            account to use the Service.
          </li>
          <li>
            <b>Usage Data</b> refers to data collected automatically, either
            generated by the use of the Service or from the Service
            infrastructure itself.
          </li>
          <li>
            <b>You</b> means the individual accessing or using the Service, or
            the company, or other legal entity on behalf of which such
            individual is accessing or using the Service, as applicable.
          </li>
        </ul>

        <h2 className="text-2xl font-bold text-[#CFABFA] mt-10 mb-4">
          Collecting and Using Your Personal Data
        </h2>
        <h3 className="text-xl font-semibold mb-2">Types of Data Collected</h3>
        <h4 className="font-semibold mb-1">Personal Data</h4>
        <p className="mb-4">
          While using our Service, we may ask you to provide us with certain
          personally identifiable information that can be used to contact or
          identify you. Personally identifiable information may include, but is
          not limited to:
        </p>
        <ul className="mb-4 list-disc list-inside text-[#CFABFA]">
          <li>Email address</li>
          <li>First name and last name</li>
          <li>Phone number</li>
          <li>Usage Data</li>
        </ul>
        <h4 className="font-semibold mb-1">Usage Data</h4>
        <p className="mb-4">
          Usage Data is collected automatically when using the Service. Usage
          Data may include information such as your device's IP address, browser
          type, browser version, the pages of our Service that you visit, the
          time and date of your visit, the time spent on those pages, unique
          device identifiers and other diagnostic data.
        </p>
        <h4 className="font-semibold mb-1">
          Information from Third-Party Social Media Services
        </h4>
        <p className="mb-4">
          The Company allows you to create an account and log in to use the
          Service through the following Third-party Social Media Services:
          Google, Facebook, Instagram, Twitter, LinkedIn.
        </p>

        <h3 className="text-xl font-semibold mb-2">
          Use of Your Personal Data
        </h3>
        <ul className="mb-4 list-disc list-inside text-[#CFABFA]">
          <li>
            To provide and maintain our Service, including to monitor the usage
            of our Service.
          </li>
          <li>To manage your Account.</li>
          <li>For the performance of a contract.</li>
          <li>
            To contact you by email, telephone, SMS, or other forms of
            electronic communication.
          </li>
          <li>
            To provide you with news, special offers, and general information.
          </li>
          <li>To manage your requests.</li>
          <li>For business transfers.</li>
          <li>
            For other purposes such as data analysis, identifying usage trends,
            and determining the effectiveness of our promotional campaigns.
          </li>
        </ul>

        <h3 className="text-xl font-semibold mb-2">
          Legal Basis for Processing Personal Data (EEA Users)
        </h3>
        <ul className="mb-4 list-disc list-inside text-[#CFABFA]">
          <li>Consent</li>
          <li>Contractual Necessity</li>
          <li>Legitimate Interest</li>
          <li>Legal Obligation</li>
          <li>Vital Interest</li>
        </ul>

        <h3 className="text-xl font-semibold mb-2">
          Retention of Your Personal Data
        </h3>
        <p className="mb-4">
          The Company will retain your Personal Data only for as long as is
          necessary for the purposes set out in this Privacy Policy, to comply
          with legal obligations, resolve disputes, and enforce agreements.
        </p>

        <h3 className="text-xl font-semibold mb-2">
          Transfer of Your Personal Data
        </h3>
        <p className="mb-4">
          Your information may be transferred to — and maintained on — computers
          located outside of your state, province, country or other governmental
          jurisdiction where the data protection laws may differ.
        </p>

        <h3 className="text-xl font-semibold mb-2">
          Delete Your Personal Data
        </h3>
        <p className="mb-4">
          You have the right to delete or request that we assist in deleting the
          Personal Data that we have collected about you. You may update, amend,
          or delete your information at any time by signing in to your Account
          or contacting us.
        </p>

        <h3 className="text-xl font-semibold mb-2">
          Disclosure of Your Personal Data
        </h3>
        <p className="mb-2 font-semibold">Business Transactions</p>
        <p className="mb-4">
          If the Company is involved in a merger, acquisition or asset sale,
          your Personal Data may be transferred. We will provide notice before
          your Personal Data is transferred and becomes subject to a different
          Privacy Policy.
        </p>
        <p className="mb-2 font-semibold">Law Enforcement</p>
        <p className="mb-4">
          Under certain circumstances, the Company may be required to disclose
          your Personal Data if required to do so by law or in response to valid
          requests by public authorities.
        </p>
        <p className="mb-2 font-semibold">Other Legal Requirements</p>
        <ul className="mb-4 list-disc list-inside text-[#CFABFA]">
          <li>Comply with a legal obligation</li>
          <li>Protect and defend the rights or property of the Company</li>
          <li>
            Prevent or investigate possible wrongdoing in connection with the
            Service
          </li>
          <li>Protect the personal safety of users or the public</li>
          <li>Protect against legal liability</li>
        </ul>

        <h3 className="text-xl font-semibold mb-2">
          Security of Your Personal Data
        </h3>
        <p className="mb-4">
          The security of your Personal Data is important to us, but no method
          of transmission over the Internet or electronic storage is 100%
          secure. While we strive to use commercially acceptable means to
          protect your Personal Data, we cannot guarantee its absolute security.
        </p>

        <h3 className="text-xl font-semibold mb-2">Children's Privacy</h3>
        <p className="mb-4">
          Our Service does not address anyone under the age of 13. We do not
          knowingly collect personally identifiable information from anyone
          under the age of 13. If you are a parent or guardian and you are aware
          that your child has provided us with Personal Data, please contact us.
        </p>

        <h3 className="text-xl font-semibold mb-2">Links to Other Websites</h3>
        <p className="mb-4">
          Our Service may contain links to other websites that are not operated
          by us. If you click on a third party link, you will be directed to
          that third party's site. We strongly advise you to review the Privacy
          Policy of every site you visit.
        </p>

        <h3 className="text-xl font-semibold mb-2">
          Changes to this Privacy Policy
        </h3>
        <p className="mb-4">
          We may update our Privacy Policy from time to time. We will notify you
          of any changes by posting the new Privacy Policy on this page and
          updating the "Last updated" date.
        </p>

        <h3 className="text-xl font-semibold mb-2">Contact Us</h3>
        <p>
          If you have any questions about this Privacy Policy, you can contact
          us:
          <br />
          <span className="block ml-4">
            By email:{" "}
            <a href="mailto:info@knowhistory.xyz" className="text-[#D4E333]">
              info@knowhistory.xyz
            </a>
          </span>
        </p>
      </div>
    </main>
  );
}
